name: Update source to crowdin

on:
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - crowdin

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: crowdin action
        uses: crowdin/github-action@v1.19.0
        with:
          upload_sources: true
          upload_sources_args: "--delete-obsolete"
          upload_translations: false
          download_translations: false
          dryrun_action: false

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
