on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: repo-sync-1.0
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/dapr/docs.git"
          source_branch: "v1.0"
          destination_branch: "v1.0/source_site"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: repo-sync-1.1
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/dapr/docs.git"
          source_branch: "v1.1"
          destination_branch: "v1.1/source_site"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: repo-sync-1.2
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/dapr/docs.git"
          source_branch: "v1.2"
          destination_branch: "v1.2/source_site"
          github_token: ${{ secrets.GITHUB_TOKEN }}
