project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "./src/"
preserve_hierarchy: true
files:
    - source: "/content/**/*.*"
      translation: "/translated_content/%locale_with_underscore%/**/%original_file_name%"