name: github pages

on:
  push:
    branches:
      - "%%tag%%"
  pull_request:
    branches:
      - "%%tag%%"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Setup Docsy and Build
        run: |
          git submodule update --init --recursive 
          cd daprdocs
          chmod a+x ./update_config_zh.sh
          ./update_config_zh.sh
          sudo npm install --save
          hugo --minify
