name: Update crowdin data to README.md

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  crowdin-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: update crowdin data
        run: |
          npm install -g @awesome-crowdin/crowdin-contributors
          crowdin-contributors -p=444716 -o=- --maxContributors=100 --mimimumWordsContributed=100 -t=${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update crowdin data in README.md
