name: V1.1 Update source to crowdin

on:
  schedule:
    - cron: "11 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - crowdin

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version_tag:
          - v1.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.version_tag }}/translate_site
      - name: crowdin action
        uses: crowdin/github-action@1.4.1
        with:
          upload_sources: true
          upload_sources_args: "--delete-obsolete"
          upload_translations: false
          download_translations: false
          dryrun_action: false
          crowdin_branch_name: ${{ matrix.version_tag }}_translate_site

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
