name: github pages

on:
  push:
    branches:
      - translate/v0.11
  pull_request:
    branches:
      - translate/v0.11

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Setup Docsy and Build
        run: |
          rm daprdocs/config.toml
          cp zh/github.pages.config.toml daprdocs/config.toml
          mkdir daprdocs/content/zh/
          cp -r zh/daprdocs/content/en/* daprdocs/content/zh/
          cd daprdocs
          git submodule update --init --recursive 
          sudo npm install -D --save autoprefixer 
          sudo npm install -D --save postcss-cli
          hugo --minify
