name: Sync translations from dapr/docs

on:
  # schedule:
  #   - cron: "10 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - dapr/docs
      - pr_to_docs

jobs:
  sync_zh_docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version_tag:
          - v1.0
          # - v1.1
          # - v1.2
          # - v1.3
          # - v1.4
          # - v1.5

    steps:
      - name: Checkout content
        uses: actions/checkout@v2
        with:
          repository: dapr/docs
          ref: ${{ matrix.version_tag }}
          submodules: true


      - name: update docs_zh submodule
        run: |
          cd "translations/docs-zh"
          git checkout origin/${{ matrix.version_tag }}_content
          git pull origin/${{ matrix.version_tag }}_content --ff-only

      - name: permissions
        #   https://stackoverflow.com/questions/11774397/git-push-error-unable-to-unlink-old-permission-denied/26950991#26950991
        run: |
          sudo chmod -R 777 .
          git config core.filemode false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_TO_DOCS_ZH }}
          commit-message: Update content
          committer: newbe36524 <newbe36524@users.noreply.github.com>
          # https://github.com/apps/dco
          signoff: true
          delete-branch: true
          push-to-fork: dapr-cn/docs
          branch: ${{ matrix.version_tag }}/source
          title: "Update translation about zh_hans for ${{ matrix.version_tag }}"
          labels: |
            content update
            automated pr
          assignees: |
            newbe36524
          reviewers: |
            newbe36524
          team-reviewers: |
            owners
            maintainers
