name: Sync translations from dapr-zh/docs

on:
  # schedule:
  #   - cron: "10 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - docs_zh

jobs:
  sync_zh_docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version_tag:
          - v1.0

    steps:
      - name: Checkout docs_zh
        uses: actions/checkout@v2
        with:
          repository: dapr/docs-zh
          ref: ${{ matrix.version_tag }}_content
      - name: Checkout content
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.version_tag }}/translate_site
          path: translated

      - name: Copy content
        run: |
          rm -rf content
          mkdir content
          cp -r translated/translated_content/zh_CN/* content
          mv content/content content/zh-hans
          rm -rf translated

      - name: permissions
        #   https://stackoverflow.com/questions/11774397/git-push-error-unable-to-unlink-old-permission-denied/26950991#26950991
        run: |
          sudo chmod -R 777 .
          git config core.filemode false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_TO_DOCS_ZH }}
          commit-message: Update content
          committer: dapr-cn <dapr-cn@hotmail.com> 
          signoff: true
          delete-branch: true
          title: "[WIP] Update content"
          labels: |
            content update
            automated pr
          assignees: |
            newbe36524
            skyao
          reviewers: |
            newbe36524
            skyao
          team-reviewers: |
            owners
            maintainers
