name: "Issue volunteer assignment"

on: [issue_comment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: bhermann/issue-volunteer@v0.1.12
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
